name: quiz-app

on:
  push:
    branches: [main, dev]

jobs:
  quiz-app-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install node packages
        run: npm ci --legacy-peer-deps
      - name: Lint
        run: npx nx run quiz-app:lint
      - name: Test
        run: npx nx test --coverage
